version: "3"
services:
  nginx:
    image: projectwithdocker_nginx:latest
    volumes:
      - ./tmp/nginx:/var/log/nginx/log
    depends_on:
      - project
    ports:
      - 80:80
    restart: always
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
  project:
      image: projectwithdocker_project:latest
      restart: always
      volumes:
        - ./project:/project
      command:  node ./bin/www
      depends_on:
          - mysql_project
      ports:
        - 3000
      deploy:
        replicas: 1
        placement:
          constraints: [node.role == worker]
  mysql_project:
      image: mysql:latest
      restart: always
      volumes:
        - ./mysql/:/docker-entrypoint-initdb.d
        - ./tmp/mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=project
        - MYSQL_ROOT_PASSWORD=PINA#3996
      deploy:
        placement:
          constraints: [node.role == manager]
