version: "3"
services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./tmp/nginx:/var/log/nginx/log
    depends_on:
      - project
    external_links:
      - project:project
    ports:
      - 80:80
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
  project:
      build:
        context: ./project
      volumes:
        - ./project:/project
      command:  node ./bin/www
      external_links:
        - mysql_project:mysql_project
      depends_on:
          - mysql_project
      ports:
        - 3000
      deploy:
        replicas: 3
        placement:
          constraints: [node.role == worker]
  mysql_project:
      image: mysql:latest
      container_name: mysql_project
      volumes:
        - ./mysql/:/docker-entrypoint-initdb.d
        - ./tmp/mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=project
        - MYSQL_ROOT_PASSWORD=PINA#3996
      deploy:
        placement:
          constraints: [node.role == manager]
